---
- name: Deploy web app
  hosts: all # имя хоста, который мы создадим Vagrant`om
  become: yes # Установка Docker через sudo
  gather_facts: false
  tasks: # Перечисляем задачи которые выполнит наш playbook
    - name: Update and upgrade apt packages
      become: true
      apt:
        #upgrade: yes
        update_cache: yes

    - name: Install docker packages # устанавливаем пакеты необходимые для установки докера
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: Add Docker s official GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify that we have the key with the fingerprint
      become: yes
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

        

    - name: Run container
      shell:
        cmd: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

    # - name: Set up the stable repository # добавляем репозиторий докера
    #   become: yes
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    #     state: present
    #   tags:
    #     - docker


    - name: Install docker # установка докера
      become: yes
      apt:
        name: docker-ce
        state: present
      tags:
        - docker

    - name: Add remote "vagrant" user to "docker" group
      become: yes
      user:
        name: vagrant
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Install docker-compose
      become: yes
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0777

    - name: Copy project # Копируем проект с хост машины в созданную через vagrant
      become: yes
      copy: 
        src=project 
        dest=/home/vagrant
        
    - name: reset ssh connection # чтобы применились права на использование docker, необходимо перелогиниться
      meta: reset_connection

    - name: Run container
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /home/vagrant/project
        
