---
- name: Deploy web app
  hosts: DynamicWeb # имя хоста, который мы создадим Vagrant`om
  become: yes # Установка Docker через sudo
  gather_facts: false
  tasks: # Перечисляем задачи которые выполнит наш playbook

    - name: install epel-release
      yum:
        state: present
        name:
          - epel-release
    - name: Install docker packages # устанавливаем пакеты необходимые для установки докера
      become: yes
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: install epel-release
      yum:
        state: present
        name:
          - docker
    
    - name: start openvpn@server
      service:
        name: docker
        state: started
        enabled: true


    - name: Add remote "vagrant" user to "docker" group
      become: yes
      user:
        name: vagrant
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Install docker-compose
      become: yes
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0777

    - name: Copy project # Копируем проект с хост машины в созданную через vagrant
      copy: 
        src=project 
        dest=/home/vagrant
        
    - name: reset ssh connection # чтобы применились права на использование docker, необходимо перелогиниться
      meta: reset_connection

    - name: Run container
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /home/vagrant/project
